name: misskey_client
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-262.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod:
  riverpod_generator:
  riverpod_annotation:
  freezed:
  freezed_annotation:
  json_annotation:
  retrofit:
  dio:
  url_launcher:
  uuid:
  flutter_secure_storage:
  go_router:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable:
  retrofit_generator:

flutter:
  uses-material-design: true
  fonts: 
    - family: LINESeedJP
      fonts:
        - asset: assets/fonts/LINESeedJP_A_OTF_Th.otf
          weight: 300
        - asset: assets/fonts/LINESeedJP_A_OTF_Rg.otf
          weight: 400
        - asset: assets/fonts/LINESeedJP_A_OTF_Bd.otf
          weight: 700
        - asset: assets/fonts/LINESeedJP_A_OTF_Eb.otf
          weight: 900